version: '3'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: ${MONGODB_URI}
      REE_API_URL: ${REE_API_URL}
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: energy-balance
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
